arrowParens: avoid
bracketSpacing: true
# endOfLine: auto
importOrder: ['<THIRD_PARTY_MODULES>', '^[./]']
importOrderParserPlugins: ['typescript']
importOrderSeparation: true
importOrderSortSpecifiers: true
printWidth: 100
semi: false
singleQuote: true
# tabWidth: 2
trailingComma: 'es5'
overrides:
  - files: '*.sol'
    options:
      tabWidth: 4
      singleQuote: false
