version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node:v0.28.2
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: findora-dev
      postgres_pass: i-love-findora
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'mainnet:https://prod-mainnet.prod.findora.org:8545'
      GRAPH_LOG: info # error | warn | info | debug
      node_id: findora-mainnet-graph-node
      ETHEREUM_POLLING_INTERVAL: 15000 # 15 secs
      GRAPH_ETHEREUM_TARGET_TRIGGERS_PER_BLOCK_RANGE: 300
      GRAPH_ETHEREUM_GENESIS_BLOCK_NUMBER: 1425000
      GRAPH_MAPPING_HANDLER_TIMEOUT: 30 # 30 secs
      GRAPH_GRAPHQL_QUERY_TIMEOUT: 10 # 10 secs
  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '5001:5001'
    volumes:
      - /tmp/graph-node/ipfs:/data/ipfs
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: findora-dev
      POSTGRES_PASSWORD: i-love-findora
      POSTGRES_DB: graph-node
    volumes:
      # PostgresSQL DB volume:
      - ./generated/postgres:/var/lib/postgresql/data
